### ISSUE TITLE
Request to make dependencies looser

### ISSUE THREAD

**Issue by dave-v** [ftpsolutions/python-third-party-license-file-generator#12]
Hi,

Is there a particular reason to pin specific versions of the dependencies for this package?

```py
    ...,
    install_requires=[
        'requests==2.25.1',
        'PyYAML==5.4.1'
    ],
    ...,
```

For us, it causes some dependency resolution issues, and it looks like you should be able to support older versions of these libraries (in our case the problem is with `requests`), as the latest release doesn't do anything but update the dependencies: https://github.com/ftpsolutions/python-third-party-license-file-generator/compare/2020.12.1...2021.4.23

**Comment by initialed85** [comment]
@dave-v 

> Is there a particular reason to pin specific versions of the dependencies for this package?

Hmm- I think it was just because the automated thing recommended it:

https://github.com/ftpsolutions/python-third-party-license-file-generator/pull/10
https://github.com/ftpsolutions/python-third-party-license-file-generator/pull/2

I can change it to a `>=` for you; what version of `requests` will argue the least amount with the other dependencies in your environment?

**Comment by dave-v** [comment]
> @dave-v
> 
> > Is there a particular reason to pin specific versions of the dependencies for this package?
> 
> Hmm- I think it was just because the automated thing recommended it:
> 
> #10 #2
> 
> I can change it to a `>=` for you; what version of `requests` will argue the least amount with the other dependencies in your environment?

That would be great, thanks :smile:.

We've both had conflicts with it being too high and too low. Most recently, it is because 2.26.0 is released and this package currently pins it at 2.25.1, which prevents us from upgrading, so I think `>=2.25.1` would suit us fine. But I think the main thing is that it isn't a single pinned version, so we'd be OK with `>=` for any version you deem appropriate.

**Comment by nick-solly** [comment]
Any update on this request please?

**Comment by initialed85** [comment]
Hi @nick-solly, sorry for the tardiness- @dave-v was kind enough to put up a PR for this, it's now been merged and released.

See: https://github.com/ftpsolutions/python-third-party-license-file-generator/releases/tag/2022.2.18

Gonna close this issue because I think we'll be good now- don't hesitate to open another though if I'm mistaken!
